import { FitAddon } from '@xterm/addon-fit';
import { Terminal } from '@xterm/xterm';
import './styles.css';
import type { ExecutionMode, ProviderId, ProviderStatus, TerminalMetadata, WorkspaceId } from '../shared/types';

const $ = <T extends Element = HTMLElement>(selector: string): T => { const element = document.querySelector<T>(selector); if (!element) throw new Error(`Missing element: ${selector}`); return element; };
type UiTerminal = { metadata: TerminalMetadata; terminal: Terminal; fit: FitAddon; lineBuffer: string };
const ui = { workspace: 'chat' as WorkspaceId, provider: 'claude' as ProviderId, execution: 'local' as ExecutionMode, cwd: '', activeTerminal: null as string | null, terminals: new Map<string, UiTerminal>(), providerStatus: new Map<ProviderId, ProviderStatus>() };
const providerNames: Record<ProviderId, string> = { claude: 'Claude', chatgpt: 'ChatGPT', gemini: 'Gemini', grok: 'Grok' };
const adapterCopy: Record<Exclude<ExecutionMode, 'local'>, string> = { codex: 'Codex will use Codex App Server JSON-RPC for threads, turns, streamed items, approvals, cancellation, and resume.', claude: 'Claude will use the Claude Agent SDK behind the provider-neutral Warden run model.', gemini: 'Gemini will use an official structured agent or CLI interface behind the Warden adapter.', grok: 'Grok Build will use Agent Client Protocol or its official headless interface.' };

function notice(message?: string): void { const box = $('#notice'); box.textContent = message || ''; box.toggleAttribute('hidden', !message); }
function providerBounds(): void { const host = $('#provider-host').getBoundingClientRect(); window.wardenDesk.provider.setBounds({ x: Math.round(host.left), y: Math.round(host.top), width: Math.round(host.width), height: Math.round(host.height) }); }
async function selectWorkspace(workspace: WorkspaceId): Promise<void> {
  ui.workspace = workspace; document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.classList.toggle('active', button.dataset.workspace === workspace));
  $('#provider-host').toggleAttribute('hidden', workspace !== 'chat'); $('#build-workspace').toggleAttribute('hidden', workspace !== 'build'); $('#provider-controls').toggleAttribute('hidden', workspace !== 'chat');
  $('#page-title').textContent = workspace === 'chat' ? providerNames[ui.provider] : 'Build'; $('#page-subtitle').textContent = workspace === 'chat' ? 'Persistent provider workspace' : 'Managed local terminals and structured agent adapters';
  await window.wardenDesk.state.update({ workspace });
  if (workspace === 'chat') { providerBounds(); await window.wardenDesk.provider.show(ui.provider); } else { await window.wardenDesk.provider.hide(); queueMicrotask(() => fitActiveTerminal()); }
}
async function selectProvider(id: ProviderId): Promise<void> { ui.provider = id; document.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach((button) => button.classList.toggle('active', button.dataset.provider === id)); $('#page-title').textContent = providerNames[id]; await selectWorkspace('chat'); await window.wardenDesk.provider.show(id); }
function renderProviderStatus(status: ProviderStatus): void { ui.providerStatus.set(status.id, status); if (status.id !== ui.provider) return; $('#page-subtitle').textContent = status.error || (status.loading ? 'Loading…' : status.title); document.querySelectorAll<HTMLButtonElement>('[data-action="back"]')[0].disabled = !status.canGoBack; document.querySelectorAll<HTMLButtonElement>('[data-action="forward"]')[0].disabled = !status.canGoForward; if (status.error) notice(status.error); if (status.cleared) notice(`${providerNames[status.id]} session data was cleared.`); }
function renderTabs(): void { const tabs = $('#terminal-tabs'); tabs.replaceChildren(); for (const [id, entry] of ui.terminals) { const button = document.createElement('button'); button.textContent = `${entry.metadata.name} · ${entry.metadata.status}`; button.classList.toggle('active', id === ui.activeTerminal); button.addEventListener('click', () => activateTerminal(id)); tabs.append(button); } }
function activateTerminal(id: string): void { const target = ui.terminals.get(id); if (!target) return; ui.activeTerminal = id; for (const [key, item] of ui.terminals) item.terminal.element?.toggleAttribute('hidden', key !== id); $('#terminal-empty').toggleAttribute('hidden', true); $('#terminal-state').textContent = `${target.metadata.status} · ${target.metadata.cwd}`; renderTabs(); fitActiveTerminal(); target.terminal.focus(); }
function fitActiveTerminal(): void { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (!active || ui.workspace !== 'build') return; try { active.fit.fit(); window.wardenDesk.terminal.resize(active.metadata.id, active.terminal.cols, active.terminal.rows); } catch { /* not visible yet */ } }
function attachTerminal(metadata: TerminalMetadata): void {
  const existing = ui.terminals.get(metadata.id); if (existing) { existing.metadata = metadata; renderTabs(); return; }
  const terminal = new Terminal({ cursorBlink: true, convertEol: true, fontSize: 13, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', theme: { background: '#090c0a', foreground: '#dbe9d8', cursor: '#93bf90' }, scrollback: 10000 }); const fit = new FitAddon(); terminal.loadAddon(fit); terminal.open($('#terminal-container')); terminal.element?.toggleAttribute('hidden', true);
  const entry: UiTerminal = { metadata, terminal, fit, lineBuffer: '' }; ui.terminals.set(metadata.id, entry);
  terminal.onData((data) => { window.wardenDesk.terminal.write(metadata.id, data); if (data === '\r') { const command = entry.lineBuffer.trim(); if (command) { entry.metadata.history.push(command); entry.metadata.history = entry.metadata.history.slice(-200); void window.wardenDesk.terminal.recordCommand(metadata.id, command); } entry.lineBuffer = ''; } else if (data === '\u007f') entry.lineBuffer = entry.lineBuffer.slice(0, -1); else if (!data.startsWith('\u001b') && data >= ' ') entry.lineBuffer += data; });
  activateTerminal(metadata.id);
}
async function createTerminal(restore?: TerminalMetadata): Promise<void> { if (!ui.cwd && !restore?.cwd) { notice('Choose a valid project directory first.'); return; } try { const metadata = await window.wardenDesk.terminal.create({ name: restore?.name || `Terminal ${ui.terminals.size + 1}`, cwd: restore?.cwd || ui.cwd, restoreId: restore?.id }); ui.cwd = metadata.cwd; $('#active-directory').textContent = metadata.cwd; notice(); attachTerminal(metadata); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function selectExecution(mode: ExecutionMode): void { ui.execution = mode; document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.classList.toggle('active', button.dataset.execution === mode)); $('#terminal-workspace').toggleAttribute('hidden', mode !== 'local'); $('#adapter-status').toggleAttribute('hidden', mode === 'local'); if (mode !== 'local') $('#adapter-copy').textContent = adapterCopy[mode]; else fitActiveTerminal(); }

async function initialize(): Promise<void> {
  const { state, warning } = await window.wardenDesk.state.get(); if (warning) notice(warning); ui.provider = state.selectedProvider; ui.cwd = state.recentProjects[0] || ''; $('#active-directory').textContent = ui.cwd || 'No project selected';
  for (const metadata of state.terminals) { const stopped = { ...metadata, status: 'stopped' as const }; attachTerminal(stopped); stopped && stopped.id === ui.activeTerminal; }
  document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.addEventListener('click', () => void selectWorkspace(button.dataset.workspace as WorkspaceId)));
  document.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach((button) => button.addEventListener('click', () => void selectProvider(button.dataset.provider as ProviderId)));
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach((button) => button.addEventListener('click', () => void window.wardenDesk.provider.action(ui.provider, button.dataset.action as 'back' | 'forward' | 'reload' | 'stop' | 'home')));
  document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.addEventListener('click', () => selectExecution(button.dataset.execution as ExecutionMode)));
  $('#clear-session').addEventListener('click', async () => { if (confirm(`Clear all cookies and site data for ${providerNames[ui.provider]}? You will be signed out.`)) await window.wardenDesk.provider.clearSession(ui.provider); });
  $('#choose-directory').addEventListener('click', async () => { const cwd = await window.wardenDesk.terminal.chooseDirectory(); if (cwd) { ui.cwd = cwd; $('#active-directory').textContent = cwd; notice(); } });
  $('#new-terminal').addEventListener('click', () => void createTerminal()); $('#clear-display').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; active?.terminal.clear(); });
  $('#restart-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active || active.metadata.status === 'running') return; active.terminal.dispose(); ui.terminals.delete(id); await createTerminal(active.metadata); });
  $('#close-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active) return; if (active.metadata.status === 'running' && !confirm(`Close ${active.metadata.name} and terminate its process?`)) return; await window.wardenDesk.terminal.kill(id); active.terminal.dispose(); ui.terminals.delete(id); ui.activeTerminal = ui.terminals.keys().next().value || null; if (ui.activeTerminal) activateTerminal(ui.activeTerminal); else $('#terminal-empty').removeAttribute('hidden'); renderTabs(); });
  const historyDialog = $('#history-dialog') as HTMLDialogElement; $('#show-history').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; const list = $('#history-list'); list.replaceChildren(); for (const command of active?.metadata.history || []) { const li = document.createElement('li'); li.textContent = command; list.append(li); } historyDialog.showModal(); }); $('[data-close-dialog]').addEventListener('click', () => historyDialog.close()); $('#clear-history').addEventListener('click', async () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (active) { await window.wardenDesk.terminal.clearHistory(active.metadata.id); active.metadata.history = []; } historyDialog.close(); });
  window.wardenDesk.provider.onStatus(renderProviderStatus); window.wardenDesk.terminal.onData(({ id, data }) => ui.terminals.get(id)?.terminal.write(data)); window.wardenDesk.terminal.onState((metadata) => { const item = ui.terminals.get(metadata.id); if (item) item.metadata = metadata; renderTabs(); });
  new ResizeObserver(() => { providerBounds(); fitActiveTerminal(); }).observe(document.body); window.addEventListener('beforeunload', () => void window.wardenDesk.provider.hide());
  await selectProvider(ui.provider); await selectWorkspace(state.workspace);
}
void initialize();
