import { FitAddon } from '@xterm/addon-fit';
import { Terminal } from '@xterm/xterm';
import './styles.css';
import type { BrowserProfile, ContextPack, ExecutionMode, PlatformNavigationRequest, PlatformPreset, PlatformStatus, ProjectWorkspace, ProviderAuthReport, StructuredProviderId, TerminalMetadata, WardenRun, WebPlatform, WorkspaceId } from '../shared/types';

const $ = <T extends Element = HTMLElement>(selector: string): T => { const element = document.querySelector<T>(selector); if (!element) throw new Error(`Missing element: ${selector}`); return element; };
type UiTerminal = { metadata: TerminalMetadata; terminal: Terminal; fit: FitAddon; lineBuffer: string };
const ui = { workspace: 'chat' as WorkspaceId, platformId: '', splitPlatformId: undefined as string | undefined, editingPlatformId: undefined as string | undefined, execution: 'local' as ExecutionMode, cwd: '', activeProjectId: undefined as string | undefined, activeTerminal: null as string | null, activeRun: null as string | null, runs: new Map<string, WardenRun>(), terminals: new Map<string, UiTerminal>(), platforms: new Map<string, WebPlatform>(), profiles: [] as BrowserProfile[], presets: [] as PlatformPreset[], projects: [] as ProjectWorkspace[], platformStatus: new Map<string, PlatformStatus>(), auth: new Map<StructuredProviderId, ProviderAuthReport>() };
const buildProviderNames: Record<StructuredProviderId, string> = { codex: 'Codex', claude: 'Claude Code', gemini: 'Gemini CLI', grok: 'Grok Build' };

function notice(message?: string): void { const box = $('#notice'); box.textContent = message || ''; box.toggleAttribute('hidden', !message); }
function providerBounds(): void { const host = $('#provider-host').getBoundingClientRect(); window.wardenDesk.platform.setBounds({ x: Math.round(host.left), y: Math.round(host.top), width: Math.round(host.width), height: Math.round(host.height) }); }
async function selectWorkspace(workspace: WorkspaceId): Promise<void> {
  ui.workspace = workspace; document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.classList.toggle('active', button.dataset.workspace === workspace));
  $('#provider-host').toggleAttribute('hidden', workspace !== 'chat'); $('#build-workspace').toggleAttribute('hidden', workspace !== 'build'); $('#browser-toolbar').toggleAttribute('hidden', workspace !== 'chat');
  await window.wardenDesk.state.update({ workspace });
  if (ui.activeProjectId) await window.wardenDesk.project.update(ui.activeProjectId, { workspace });
  if (workspace === 'chat') { providerBounds(); if (ui.platformId) await window.wardenDesk.platform.show(ui.platformId, ui.splitPlatformId); } else { await window.wardenDesk.platform.hide(); queueMicrotask(() => fitActiveTerminal()); }
}
async function selectPlatform(id: string, splitId?: string): Promise<void> { const platform = ui.platforms.get(id); if (!platform?.enabled) return; ui.platformId = id; ui.splitPlatformId = splitId; renderPlatforms(); await window.wardenDesk.state.update({ selectedPlatformId: id }); if (ui.activeProjectId) await window.wardenDesk.project.update(ui.activeProjectId, { selectedPlatformId: id, splitPlatformId: splitId }); await selectWorkspace('chat'); await window.wardenDesk.platform.show(id, splitId); }
function renderProviderStatus(status: PlatformStatus): void { ui.platformStatus.set(status.id, status); if (status.id !== ui.platformId || ui.workspace !== 'chat') return; const reload = $('#reload-stop') as HTMLButtonElement; reload.dataset.action = status.loading ? 'stop' : 'reload'; reload.textContent = status.loading ? '■' : '↻'; reload.title = status.loading ? 'Stop loading' : 'Reload (Ctrl+R)'; $('#loading-state').textContent = status.error ? 'Load error' : status.loading ? 'Loading…' : ''; document.querySelector<HTMLButtonElement>('[data-action="back"]')!.disabled = !status.canGoBack; document.querySelector<HTMLButtonElement>('[data-action="forward"]')!.disabled = !status.canGoForward; if (status.error) notice(status.error); if (status.cleared) notice('Configured site data was cleared. Related domains in the shared profile may also have been affected.'); }
function renderPlatforms(): void { const root = $('#platforms'); root.replaceChildren(); const query = ($('#platform-search') as HTMLInputElement).value.trim().toLowerCase(); for (const platform of [...ui.platforms.values()].filter((item) => item.name.toLowerCase().includes(query) || item.category.toLowerCase().includes(query)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || a.order - b.order)) { const button = document.createElement('button'); button.dataset.platformId = platform.id; button.classList.toggle('active', platform.id === ui.platformId); button.disabled = !platform.enabled; const icon = document.createElement('i'); if (platform.icon.kind === 'url') { const image = document.createElement('img'); image.src = platform.icon.value; image.alt = ''; icon.append(image); } else icon.textContent = platform.icon.value; const name = document.createTextNode(platform.name); const meta = document.createElement('span'); meta.className = 'platform-meta'; meta.textContent = platform.category; button.append(icon, name, meta); button.addEventListener('click', () => void selectPlatform(platform.id)); root.append(button); } }
function renderProjects(): void { const select = $('#project-picker') as HTMLSelectElement; select.replaceChildren(new Option('No project selected', '')); for (const project of ui.projects) select.add(new Option(project.name, project.id)); select.value = ui.activeProjectId || ''; }
async function activateProject(id: string): Promise<void> { if (!id) return; const project = await window.wardenDesk.project.activate(id); ui.activeProjectId = project.id; ui.cwd = project.cwd; ui.execution = project.executionMode; ui.platformId = project.selectedPlatformId && ui.platforms.has(project.selectedPlatformId) ? project.selectedPlatformId : ui.platformId; ui.splitPlatformId = project.splitPlatformId; $('#active-directory').textContent = project.cwd; $('#agent-directory').textContent = project.cwd; selectExecution(project.executionMode); await refreshRuns(); renderProjects(); await selectWorkspace(project.workspace); }
function renderTabs(): void { const tabs = $('#terminal-tabs'); tabs.replaceChildren(); for (const [id, entry] of ui.terminals) { const button = document.createElement('button'); button.textContent = `${entry.metadata.name} · ${entry.metadata.status}`; button.classList.toggle('active', id === ui.activeTerminal); button.addEventListener('click', () => activateTerminal(id)); tabs.append(button); } }
function activateTerminal(id: string): void { const target = ui.terminals.get(id); if (!target) return; ui.activeTerminal = id; for (const [key, item] of ui.terminals) item.terminal.element?.toggleAttribute('hidden', key !== id); $('#terminal-empty').toggleAttribute('hidden', true); $('#terminal-state').textContent = `${target.metadata.status} · ${target.metadata.cwd}`; renderTabs(); fitActiveTerminal(); target.terminal.focus(); }
function fitActiveTerminal(): void { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (!active || ui.workspace !== 'build') return; try { active.fit.fit(); window.wardenDesk.terminal.resize(active.metadata.id, active.terminal.cols, active.terminal.rows); } catch { /* not visible yet */ } }
function attachTerminal(metadata: TerminalMetadata): void {
  const existing = ui.terminals.get(metadata.id); if (existing) { existing.metadata = metadata; renderTabs(); return; }
  const terminal = new Terminal({ cursorBlink: true, convertEol: true, fontSize: 13, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', theme: { background: '#090c0a', foreground: '#dbe9d8', cursor: '#93bf90' }, scrollback: 10000 }); const fit = new FitAddon(); terminal.loadAddon(fit); terminal.open($('#terminal-container')); terminal.element?.toggleAttribute('hidden', true);
  const entry: UiTerminal = { metadata, terminal, fit, lineBuffer: '' }; ui.terminals.set(metadata.id, entry);
  terminal.onData((data) => { window.wardenDesk.terminal.write(metadata.id, data); if (data === '\r') { const command = entry.lineBuffer.trim(); if (command) { entry.metadata.history.push(command); entry.metadata.history = entry.metadata.history.slice(-200); void window.wardenDesk.terminal.recordCommand(metadata.id, command); } entry.lineBuffer = ''; } else if (data === '\u007f') entry.lineBuffer = entry.lineBuffer.slice(0, -1); else if (!data.startsWith('\u001b') && data >= ' ') entry.lineBuffer += data; });
  activateTerminal(metadata.id);
}
async function createTerminal(restore?: TerminalMetadata): Promise<void> { if (!ui.cwd && !restore?.cwd) { notice('Choose a valid project directory first.'); return; } try { const metadata = await window.wardenDesk.terminal.create({ name: restore?.name || `Terminal ${ui.terminals.size + 1}`, cwd: restore?.cwd || ui.cwd, restoreId: restore?.id }); ui.cwd = metadata.cwd; $('#active-directory').textContent = metadata.cwd; if (!ui.activeProjectId) { const project = await window.wardenDesk.project.create({ cwd: metadata.cwd }); ui.projects = await window.wardenDesk.project.list(); ui.activeProjectId = project.id; renderProjects(); } notice(); attachTerminal(metadata); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function authStateLabel(report?: ProviderAuthReport): string { if (!report) return 'checking…'; return report.state.replaceAll('_', ' '); }
function activeBuildProvider(): StructuredProviderId | null { return ui.execution === 'local' ? null : ui.execution; }
function renderAuthStatus(): void {
  const provider = activeBuildProvider(); if (!provider) return; const report = ui.auth.get(provider);
  $(`#auth-tab-${provider}`).textContent = authStateLabel(report);
  $('#auth-title').textContent = report ? `${buildProviderNames[provider]} · ${authStateLabel(report)}` : `Checking ${buildProviderNames[provider]}…`;
  $('#auth-detail').textContent = report?.detail || 'Authentication remains owned by the official local client.';
  const apiInput = document.querySelector<HTMLInputElement>('input[name="billing-source"][value="api_key"]')!; apiInput.disabled = !report?.apiFallbackAvailable;
  $('#api-source-label').classList.toggle('disabled', apiInput.disabled);
  if (apiInput.disabled && apiInput.checked) (document.querySelector<HTMLInputElement>('input[name="billing-source"][value="subscription"]')!).checked = true;
  const button = $('#start-run') as HTMLButtonElement; button.textContent = `Start ${buildProviderNames[provider]} run`; button.disabled = !report?.canStart && !report?.apiFallbackAvailable;
}
async function refreshProviderAuth(): Promise<void> { try { const reports = await window.wardenDesk.runs.providers(); ui.auth = new Map(reports.map((report) => [report.provider, report])); for (const report of reports) $(`#auth-tab-${report.provider}`).textContent = authStateLabel(report); renderAuthStatus(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function selectExecution(mode: ExecutionMode): void { ui.execution = mode; document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.classList.toggle('active', button.dataset.execution === mode)); $('#terminal-workspace').toggleAttribute('hidden', mode !== 'local'); $('#agent-workspace').toggleAttribute('hidden', mode === 'local'); if (ui.activeProjectId) void window.wardenDesk.project.update(ui.activeProjectId, { executionMode: mode }); if (mode === 'local') fitActiveTerminal(); else renderAuthStatus(); }

function runSummary(run: WardenRun): string { const recent = run.events.slice(-80).map((event) => { if (event.type === 'message.delta') return String(event.payload.delta || ''); if (event.type === 'command.started') return `\n$ ${String(event.payload.command || '')}\n`; if (event.type === 'command.completed') return `[exit ${String(event.payload.exitCode ?? '?')}]\n${String(event.payload.output || '').slice(-3000)}\n`; if (event.type === 'file.changed') return `[files changed: ${JSON.stringify(event.payload.changes || [])}]\n`; if (event.type === 'approval.requested') return `[approval required: ${String(event.payload.detail || '')}]\n`; if (event.type === 'run.completed') return `\nCompleted: ${String(event.payload.finalMessage || '')}`; if (event.type === 'run.failed') return `\nFailed: ${String(event.payload.error || '')}`; return ''; }).join(''); return [`Run ${run.id}`, `Provider: ${run.provider}`, `Authentication / billing: ${run.auth?.source || 'unknown'}${run.auth?.entitlement ? ` · ${run.auth.entitlement}` : ''}`, `Status: ${run.status}`, `Project: ${run.cwd}`, `Session: ${run.threadId || 'not started'}`, `Turn: ${run.turnId || 'not started'}`, `Changed files: ${run.evidence.changedFiles.join(', ') || 'none recorded'}`, `Tests: ${run.evidence.tests.map((test) => `${test.command} → ${test.exitCode}`).join('; ') || 'none recorded'}`, `Proof: local=${run.proof.local}, brain=${run.proof.brain}${run.proof.detail ? ` (${run.proof.detail})` : ''}`, '', recent || run.error || 'Waiting for events…'].join('\n'); }
function renderApprovals(run?: WardenRun): void { const root = $('#approval-list'); root.replaceChildren(); for (const approval of run?.approvals.filter((item) => item.status === 'pending') || []) { const card = document.createElement('div'); card.className = 'approval'; const title = document.createElement('strong'); title.textContent = approval.title; const detail = document.createElement('code'); detail.textContent = approval.detail; const once = document.createElement('button'); once.textContent = 'Approve once'; once.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'approve', 'once')); const session = document.createElement('button'); session.textContent = 'Approve session'; session.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'approve', 'session')); const deny = document.createElement('button'); deny.textContent = 'Deny'; deny.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'deny', 'once')); card.append(title, detail, once, session, deny); root.append(card); } }
function renderRun(run?: WardenRun): void { if (!run) { $('#run-detail').textContent = 'Select or start a run.'; renderApprovals(); return; } ui.activeRun = run.id; ui.cwd = run.cwd; if (['codex', 'claude', 'gemini', 'grok'].includes(run.provider) && ui.execution !== run.provider) selectExecution(run.provider as StructuredProviderId); $('#active-directory').textContent = run.cwd; $('#agent-directory').textContent = run.cwd; $('#run-detail').textContent = runSummary(run); renderApprovals(run); document.querySelectorAll<HTMLButtonElement>('.run-card').forEach((card) => card.classList.toggle('active', card.dataset.runId === run.id)); }
function renderRuns(): void { const root = $('#runs'); root.replaceChildren(); const runs = [...ui.runs.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); for (const run of runs) { const button = document.createElement('button'); button.className = 'run-card'; button.dataset.runId = run.id; const title = document.createElement('strong'); title.textContent = run.prompt.split('\n')[0].slice(0, 80) || run.project; const meta = document.createElement('span'); meta.textContent = `${run.provider} · ${run.status} · ${new Date(run.updatedAt).toLocaleString()}`; button.append(title, meta); button.addEventListener('click', () => renderRun(run)); root.append(button); } if (ui.activeRun) renderRun(ui.runs.get(ui.activeRun)); }
async function refreshRuns(): Promise<void> { const runs = await window.wardenDesk.runs.list(ui.activeProjectId); ui.runs = new Map(runs.map((run) => [run.id, run])); if ((!ui.activeRun || !ui.runs.has(ui.activeRun)) && runs[0]) ui.activeRun = runs[0].id; renderRuns(); }
async function respondApproval(runId: string, approvalId: string, decision: 'approve' | 'deny', scope: 'once' | 'session'): Promise<void> { try { await window.wardenDesk.runs.approve(runId, approvalId, decision, scope); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function contextText(pack: ContextPack): string { return [`Project: ${pack.project}`, `Directory: ${pack.cwd}`, `Branch: ${pack.branch || 'unknown'}`, `Git status:\n${pack.gitStatus || '(clean)'}`, `Instructions: ${pack.instructionFiles.map((file) => file.path).join(', ') || 'none'}`, `Skills: ${pack.skills.join(', ') || 'none'}`, `Local scoped memories: ${pack.memories.length}`, `Warden Brain: ${pack.brainContext ? 'attached' : 'unavailable'}`, ...pack.warnings.map((warning) => `Warning: ${warning}`)].join('\n'); }
function approveApiBilling(provider: StructuredProviderId): Promise<boolean> { return new Promise((resolve) => { const dialog = $('#api-warning-dialog') as HTMLDialogElement; $('#api-warning-copy').textContent = `${buildProviderNames[provider]} will use an API key for this run. Provider usage charges may apply. Warden will not remember this approval.`; const finish = (approved: boolean): void => { dialog.close(); resolve(approved); }; ($('#confirm-api-run') as HTMLButtonElement).onclick = () => finish(true); ($('#cancel-api-run') as HTMLButtonElement).onclick = () => finish(false); ($('#cancel-api-run-secondary') as HTMLButtonElement).onclick = () => finish(false); dialog.addEventListener('cancel', () => resolve(false), { once: true }); dialog.showModal(); }); }

function closePlatformMenu(): void { $('#platform-menu').toggleAttribute('hidden', true); $('#platform-overflow').setAttribute('aria-expanded', 'false'); }
function domainLines(values: string[]): string { return values.join('\n'); }
function readDomainLines(selector: string): string[] { return [...new Set(($(selector) as HTMLTextAreaElement).value.split(/[\s,]+/).map((value) => value.trim()).filter(Boolean))]; }
function fillPlatformForm(platform?: WebPlatform): void {
  ui.editingPlatformId = platform?.id; $('#platform-dialog-title').textContent = platform ? `Edit ${platform.name}` : 'Add AI platform'; ($('#platform-preset') as HTMLSelectElement).value = ''; ($('#platform-name') as HTMLInputElement).value = platform?.name || ''; ($('#platform-url') as HTMLInputElement).value = platform?.startUrl || ''; ($('#platform-icon') as HTMLInputElement).value = platform?.icon.value || ''; ($('#platform-category') as HTMLSelectElement).value = platform?.category || 'Other'; ($('#platform-profile') as HTMLSelectElement).value = platform?.browserProfileId || ui.profiles[0]?.id || ''; ($('#platform-domains') as HTMLTextAreaElement).value = domainLines(platform?.trustedFirstPartyDomains || []); ($('#platform-auth-domains') as HTMLTextAreaElement).value = domainLines(platform?.trustedAuthDomains || []); ($('#platform-enabled') as HTMLInputElement).checked = platform?.enabled ?? true; ($('#platform-pinned') as HTMLInputElement).checked = platform?.pinned ?? false; ($('#platform-main') as HTMLInputElement).checked = platform?.allowMainView ?? true; ($('#platform-split') as HTMLInputElement).checked = platform?.allowSplitView ?? true;
}
function openPlatformDialog(platform?: WebPlatform): void { fillPlatformForm(platform); ($('#platform-preset') as HTMLSelectElement).disabled = Boolean(platform); ($('#platform-dialog') as HTMLDialogElement).showModal(); }
async function savePlatformForm(event: SubmitEvent): Promise<void> { event.preventDefault(); const iconValue = ($('#platform-icon') as HTMLInputElement).value.trim(); const input = { name: ($('#platform-name') as HTMLInputElement).value, startUrl: ($('#platform-url') as HTMLInputElement).value, icon: { kind: iconValue.startsWith('https://') ? 'url' as const : 'text' as const, value: iconValue }, category: ($('#platform-category') as HTMLSelectElement).value as WebPlatform['category'], browserProfileId: ($('#platform-profile') as HTMLSelectElement).value, trustedFirstPartyDomains: readDomainLines('#platform-domains'), trustedAuthDomains: readDomainLines('#platform-auth-domains'), enabled: ($('#platform-enabled') as HTMLInputElement).checked, pinned: ($('#platform-pinned') as HTMLInputElement).checked, allowMainView: ($('#platform-main') as HTMLInputElement).checked, allowSplitView: ($('#platform-split') as HTMLInputElement).checked }; try { const platform = ui.editingPlatformId ? await window.wardenDesk.platform.update(ui.editingPlatformId, input) : await window.wardenDesk.platform.create(input); ui.platforms.set(platform.id, platform); ui.platformId = platform.id; ($('#platform-dialog') as HTMLDialogElement).close(); renderPlatforms(); await selectPlatform(platform.id); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function applyPreset(key: string): void { const preset = ui.presets.find((item) => item.key === key); if (!preset) return; ($('#platform-name') as HTMLInputElement).value = preset.name; ($('#platform-url') as HTMLInputElement).value = preset.startUrl; ($('#platform-icon') as HTMLInputElement).value = preset.icon.value; ($('#platform-category') as HTMLSelectElement).value = preset.category; ($('#platform-domains') as HTMLTextAreaElement).value = domainLines(preset.trustedFirstPartyDomains); ($('#platform-auth-domains') as HTMLTextAreaElement).value = domainLines(preset.trustedAuthDomains); }
async function navigationChoice(request: PlatformNavigationRequest): Promise<void> { const dialog = $('#navigation-dialog') as HTMLDialogElement; $('#navigation-copy').textContent = `${request.platformName} wants to ${request.reason === 'popup' ? 'open' : 'navigate to'} ${request.domain}. This is not currently trusted for this platform.`; $('#navigation-url').textContent = request.url; dialog.dataset.requestId = request.requestId; dialog.showModal(); }
async function resolveNavigation(decision: 'allow_once' | 'trust' | 'external' | 'cancel'): Promise<void> { const dialog = $('#navigation-dialog') as HTMLDialogElement; const requestId = dialog.dataset.requestId; dialog.close(); if (!requestId) return; try { await window.wardenDesk.platform.resolveNavigation(requestId, decision); if (decision === 'trust') { const platforms = await window.wardenDesk.platform.list(); ui.platforms = new Map(platforms.map((item) => [item.id, item])); } } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function openClearDialog(): void { const platform = ui.platforms.get(ui.platformId); if (!platform) return; const profile = ui.profiles.find((item) => item.id === platform.browserProfileId); $('#clear-site-copy').textContent = `This signs you out of ${platform.name} by clearing its configured origins in the shared “${profile?.name || 'unknown'}” Warden profile. It does not delete the profile, and it does not import, decrypt, or touch Chrome cookies.`; ($('#clear-site-dialog') as HTMLDialogElement).showModal(); }
function openSplitDialog(): void { const select = $('#split-platform') as HTMLSelectElement; select.replaceChildren(); for (const platform of ui.platforms.values()) if (platform.id !== ui.platformId && platform.enabled && platform.allowSplitView) select.add(new Option(platform.name, platform.id)); if (!select.options.length) return notice('No other split-view platform is available.'); ($('#split-dialog') as HTMLDialogElement).showModal(); }
async function chooseProjectDirectory(): Promise<void> { const cwd = await window.wardenDesk.terminal.chooseDirectory(); if (!cwd) return; const project = await window.wardenDesk.project.create({ cwd, browserProfileId: ui.platforms.get(ui.platformId)?.browserProfileId }); ui.projects = await window.wardenDesk.project.list(); await activateProject(project.id); notice(); }

async function initialize(): Promise<void> {
  const [{ state, warning }, platforms, presets, profiles, projects] = await Promise.all([window.wardenDesk.state.get(), window.wardenDesk.platform.list(), window.wardenDesk.platform.presets(), window.wardenDesk.platform.profiles(), window.wardenDesk.project.list()]); if (warning) notice(warning); ui.platforms = new Map(platforms.map((item) => [item.id, item])); ui.presets = presets; ui.profiles = profiles; ui.projects = projects; ui.platformId = state.selectedPlatformId && ui.platforms.has(state.selectedPlatformId) ? state.selectedPlatformId : platforms[0]?.id || ''; ui.activeProjectId = state.activeProjectId; const activeProject = projects.find((item) => item.id === ui.activeProjectId); ui.cwd = activeProject?.cwd || state.recentProjects[0] || ''; ui.splitPlatformId = activeProject?.splitPlatformId; $('#active-directory').textContent = ui.cwd || 'No project selected';
  $('#agent-directory').textContent = ui.cwd || 'No project selected'; renderProjects(); renderPlatforms();
  const presetSelect = $('#platform-preset') as HTMLSelectElement; for (const preset of presets) presetSelect.add(new Option(preset.name, preset.key)); const profileSelect = $('#platform-profile') as HTMLSelectElement; for (const profile of profiles) profileSelect.add(new Option(profile.name, profile.id));
  for (const metadata of state.terminals) { const stopped = { ...metadata, status: 'stopped' as const }; attachTerminal(stopped); stopped && stopped.id === ui.activeTerminal; }
  document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.addEventListener('click', () => void selectWorkspace(button.dataset.workspace as WorkspaceId)));
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach((button) => button.addEventListener('click', () => { if (ui.platformId) void window.wardenDesk.platform.action(ui.platformId, button.dataset.action as 'back' | 'forward' | 'reload' | 'stop' | 'home'); }));
  document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.addEventListener('click', () => selectExecution(button.dataset.execution as ExecutionMode)));
  document.querySelectorAll<HTMLInputElement>('input[name="billing-source"]').forEach((input) => input.addEventListener('change', renderAuthStatus));
  $('#project-picker').addEventListener('change', () => void activateProject(($('#project-picker') as HTMLSelectElement).value)); $('#platform-search').addEventListener('input', renderPlatforms); $('#add-platform').addEventListener('click', () => openPlatformDialog()); $('#restore-platform').addEventListener('click', async () => { const removed = await window.wardenDesk.platform.removed(); if (!removed.length) return notice('No removed platforms are available to restore.'); const choice = removed.length === 1 ? removed[0].name : prompt(`Enter the platform to restore:\n${removed.map((item) => item.name).join('\n')}`); const target = removed.find((item) => item.name.toLowerCase() === choice?.trim().toLowerCase()); if (!target) return choice && notice('No removed platform matched that name.'); const restored = await window.wardenDesk.platform.restore(target.id); ui.platforms.set(restored.id, restored); renderPlatforms(); await selectPlatform(restored.id); }); presetSelect.addEventListener('change', () => applyPreset(presetSelect.value)); ($('#platform-form') as HTMLFormElement).addEventListener('submit', (event) => void savePlatformForm(event));
  $('#new-profile').addEventListener('click', async () => { const name = prompt('Name this Warden browser profile. Profiles share cookies only with platforms assigned to the same profile.'); if (!name) return; try { const profile = await window.wardenDesk.platform.createProfile(name); ui.profiles.push(profile); profileSelect.add(new Option(profile.name, profile.id)); profileSelect.value = profile.id; } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#platform-overflow').addEventListener('click', () => { const menu = $('#platform-menu'); const opening = menu.hasAttribute('hidden'); menu.toggleAttribute('hidden', !opening); $('#platform-overflow').setAttribute('aria-expanded', String(opening)); const builtIn = ['platform-claude', 'platform-chatgpt', 'platform-gemini', 'platform-grok'].includes(ui.platformId); $('#menu-remove').toggleAttribute('hidden', builtIn); });
  $('#open-system').addEventListener('click', () => ui.platformId && void window.wardenDesk.platform.openExternal(ui.platformId)); $('#menu-open-system').addEventListener('click', () => { closePlatformMenu(); if (ui.platformId) void window.wardenDesk.platform.openExternal(ui.platformId); }); $('#menu-home').addEventListener('click', () => { closePlatformMenu(); if (ui.platformId) void window.wardenDesk.platform.action(ui.platformId, 'home'); }); $('#menu-reload').addEventListener('click', () => { closePlatformMenu(); if (ui.platformId) void window.wardenDesk.platform.action(ui.platformId, 'reload'); }); $('#menu-settings').addEventListener('click', () => { closePlatformMenu(); const platform = ui.platforms.get(ui.platformId); if (platform) openPlatformDialog(platform); }); $('#menu-split').addEventListener('click', () => { closePlatformMenu(); openSplitDialog(); }); $('#menu-clear').addEventListener('click', () => { closePlatformMenu(); openClearDialog(); });
  const movePlatform = async (direction: -1 | 1): Promise<void> => { const ordered = [...ui.platforms.values()].sort((a, b) => a.order - b.order); const index = ordered.findIndex((item) => item.id === ui.platformId); const swap = ordered[index + direction]; const current = ordered[index]; if (!current || !swap) return; const first = await window.wardenDesk.platform.update(current.id, { order: swap.order }); const second = await window.wardenDesk.platform.update(swap.id, { order: current.order }); ui.platforms.set(first.id, first); ui.platforms.set(second.id, second); renderPlatforms(); closePlatformMenu(); }; $('#menu-move-up').addEventListener('click', () => void movePlatform(-1)); $('#menu-move-down').addEventListener('click', () => void movePlatform(1));
  $('#menu-remove').addEventListener('click', async () => { closePlatformMenu(); const platform = ui.platforms.get(ui.platformId); if (!platform || !confirm(`Remove ${platform.name} from Warden? Its browser data will not be deleted.`)) return; try { await window.wardenDesk.platform.remove(platform.id); ui.platforms.delete(platform.id); ui.platformId = [...ui.platforms.values()][0]?.id || ''; renderPlatforms(); if (ui.platformId) await selectPlatform(ui.platformId); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#confirm-clear-site').addEventListener('click', async () => { ($('#clear-site-dialog') as HTMLDialogElement).close(); try { await window.wardenDesk.platform.clearSiteData(ui.platformId); notice('Configured site data cleared. The platform must be selected again to reload.'); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }); $('#clear-cancel').addEventListener('click', () => ($('#clear-site-dialog') as HTMLDialogElement).close()); $('#clear-cancel-x').addEventListener('click', () => ($('#clear-site-dialog') as HTMLDialogElement).close());
  $('#confirm-split').addEventListener('click', async () => { const id = ($('#split-platform') as HTMLSelectElement).value; ($('#split-dialog') as HTMLDialogElement).close(); if (id) await selectPlatform(ui.platformId, id); }); $('#split-cancel').addEventListener('click', () => ($('#split-dialog') as HTMLDialogElement).close()); $('#split-cancel-x').addEventListener('click', () => ($('#split-dialog') as HTMLDialogElement).close());
  document.querySelectorAll<HTMLButtonElement>('[data-nav-decision]').forEach((button) => button.addEventListener('click', () => void resolveNavigation(button.dataset.navDecision as 'allow_once' | 'trust' | 'external' | 'cancel'))); $('#nav-cancel-x').addEventListener('click', () => void resolveNavigation('cancel'));
  $('#choose-directory').addEventListener('click', () => void chooseProjectDirectory());
  $('#agent-choose-directory').addEventListener('click', () => void chooseProjectDirectory());
  $('#preview-context').addEventListener('click', async () => { if (!ui.cwd) return notice('Choose a project directory first.'); try { const pack = await window.wardenDesk.runs.previewContext(ui.cwd); const output = $('#context-preview'); output.textContent = contextText(pack); output.removeAttribute('hidden'); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#start-run').addEventListener('click', async () => { const provider = activeBuildProvider(); const prompt = ($('#run-prompt') as HTMLTextAreaElement).value.trim(); if (!provider) return notice('Choose a structured provider first.'); if (!ui.cwd || !prompt) return notice('Choose a project and enter a build task.'); const authSource = document.querySelector<HTMLInputElement>('input[name="billing-source"]:checked')?.value === 'api_key' ? 'api_key' : 'subscription'; const report = ui.auth.get(provider); if (authSource === 'subscription' && report?.state !== 'subscription_authenticated') return notice(report?.detail || 'Subscription authentication is not ready.'); const apiFallbackApproved = authSource === 'api_key' ? await approveApiBilling(provider) : false; if (authSource === 'api_key' && !apiFallbackApproved) return notice('API-key run cancelled. No billable request was started.'); try { notice(`Starting ${buildProviderNames[provider]} run with ${authSource === 'subscription' ? 'subscription' : 'approved API-key'} authentication…`); const run = await window.wardenDesk.runs.start({ provider, prompt, cwd: ui.cwd, projectId: ui.activeProjectId, attachContext: ($('#attach-context') as HTMLInputElement).checked, authSource, apiFallbackApproved }); ui.runs.set(run.id, run); ui.activeRun = run.id; if (ui.activeProjectId) await window.wardenDesk.project.update(ui.activeProjectId, { activeRunId: run.id }); renderRuns(); renderRun(run); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); await refreshRuns(); } });
  $('#resume-run').addEventListener('click', async () => { const prompt = ($('#run-prompt') as HTMLTextAreaElement).value.trim(); if (!ui.activeRun) return notice('Select a run to resume.'); try { notice('Resuming preserved Codex thread…'); const run = await window.wardenDesk.runs.resume(ui.activeRun, prompt); ui.runs.set(run.id, run); renderRun(run); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#cancel-run').addEventListener('click', async () => { if (!ui.activeRun) return; try { await window.wardenDesk.runs.cancel(ui.activeRun); notice('Cancellation requested.'); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#generate-handoff').addEventListener('click', async () => { if (!ui.activeRun) return notice('Select a run first.'); try { const result = await window.wardenDesk.runs.handoff(ui.activeRun); $('#run-detail').textContent = `${result.content}\n\nSaved: ${result.path}`; notice('Handoff generated.'); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#save-proof').addEventListener('click', async () => { if (!ui.activeRun) return notice('Select a run first.'); try { const proof = await window.wardenDesk.runs.saveProof(ui.activeRun); notice(proof.detail); await refreshRuns(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#refresh-runs').addEventListener('click', () => void refreshRuns());
  $('#refresh-auth').addEventListener('click', () => void refreshProviderAuth());
  $('#new-terminal').addEventListener('click', () => void createTerminal()); $('#clear-display').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; active?.terminal.clear(); });
  $('#restart-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active || active.metadata.status === 'running') return; active.terminal.dispose(); ui.terminals.delete(id); await createTerminal(active.metadata); });
  $('#close-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active) return; if (active.metadata.status === 'running' && !confirm(`Close ${active.metadata.name} and terminate its process?`)) return; await window.wardenDesk.terminal.kill(id); active.terminal.dispose(); ui.terminals.delete(id); ui.activeTerminal = ui.terminals.keys().next().value || null; if (ui.activeTerminal) activateTerminal(ui.activeTerminal); else $('#terminal-empty').removeAttribute('hidden'); renderTabs(); });
  const historyDialog = $('#history-dialog') as HTMLDialogElement; $('#show-history').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; const list = $('#history-list'); list.replaceChildren(); for (const command of active?.metadata.history || []) { const li = document.createElement('li'); li.textContent = command; list.append(li); } historyDialog.showModal(); }); $('[data-close-dialog]').addEventListener('click', () => historyDialog.close()); $('#clear-history').addEventListener('click', async () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (active) { await window.wardenDesk.terminal.clearHistory(active.metadata.id); active.metadata.history = []; } historyDialog.close(); });
  window.wardenDesk.platform.onStatus(renderProviderStatus); window.wardenDesk.platform.onNavigationRequest((request) => void navigationChoice(request)); window.wardenDesk.terminal.onData(({ id, data }) => ui.terminals.get(id)?.terminal.write(data)); window.wardenDesk.terminal.onState((metadata) => { const item = ui.terminals.get(metadata.id); if (item) item.metadata = metadata; renderTabs(); });
  window.wardenDesk.runs.onChanged((run) => { if (!ui.activeProjectId || run.projectId === ui.activeProjectId) ui.runs.set(run.id, run); renderRuns(); if (ui.activeRun === run.id) renderRun(run); });
  document.addEventListener('click', (event) => { if (!(event.target as Element).closest('#platform-overflow, #platform-menu')) closePlatformMenu(); }); window.addEventListener('keydown', (event) => { if (ui.workspace !== 'chat' || !ui.platformId) return; if (event.altKey && event.key === 'ArrowLeft') { event.preventDefault(); void window.wardenDesk.platform.action(ui.platformId, 'back'); } if (event.altKey && event.key === 'ArrowRight') { event.preventDefault(); void window.wardenDesk.platform.action(ui.platformId, 'forward'); } if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === 'r') { event.preventDefault(); void window.wardenDesk.platform.action(ui.platformId, 'reload'); } });
  new ResizeObserver(() => { providerBounds(); fitActiveTerminal(); }).observe(document.body); window.addEventListener('beforeunload', () => void window.wardenDesk.platform.hide());
  await Promise.all([refreshRuns(), refreshProviderAuth()]); if (activeProject) { ui.execution = activeProject.executionMode; selectExecution(ui.execution); } if (ui.platformId && state.workspace === 'chat') await selectPlatform(ui.platformId, ui.splitPlatformId); else await selectWorkspace(state.workspace);
}
void initialize();
