import { FitAddon } from '@xterm/addon-fit';
import { Terminal } from '@xterm/xterm';
import './styles.css';
import type { ContextPack, ExecutionMode, ProviderId, ProviderStatus, TerminalMetadata, WardenRun, WorkspaceId } from '../shared/types';

const $ = <T extends Element = HTMLElement>(selector: string): T => { const element = document.querySelector<T>(selector); if (!element) throw new Error(`Missing element: ${selector}`); return element; };
type UiTerminal = { metadata: TerminalMetadata; terminal: Terminal; fit: FitAddon; lineBuffer: string };
const ui = { workspace: 'chat' as WorkspaceId, provider: 'claude' as ProviderId, execution: 'local' as ExecutionMode, cwd: '', activeTerminal: null as string | null, activeRun: null as string | null, runs: new Map<string, WardenRun>(), terminals: new Map<string, UiTerminal>(), providerStatus: new Map<ProviderId, ProviderStatus>() };
const providerNames: Record<ProviderId, string> = { claude: 'Claude', chatgpt: 'ChatGPT', gemini: 'Gemini', grok: 'Grok' };
const adapterCopy: Record<Exclude<ExecutionMode, 'local'>, string> = { codex: 'Codex will use Codex App Server JSON-RPC for threads, turns, streamed items, approvals, cancellation, and resume.', claude: 'Claude will use the Claude Agent SDK behind the provider-neutral Warden run model.', gemini: 'Gemini will use an official structured agent or CLI interface behind the Warden adapter.', grok: 'Grok Build will use Agent Client Protocol or its official headless interface.' };

function notice(message?: string): void { const box = $('#notice'); box.textContent = message || ''; box.toggleAttribute('hidden', !message); }
function providerBounds(): void { const host = $('#provider-host').getBoundingClientRect(); window.wardenDesk.provider.setBounds({ x: Math.round(host.left), y: Math.round(host.top), width: Math.round(host.width), height: Math.round(host.height) }); }
async function selectWorkspace(workspace: WorkspaceId): Promise<void> {
  ui.workspace = workspace; document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.classList.toggle('active', button.dataset.workspace === workspace));
  $('#provider-host').toggleAttribute('hidden', workspace !== 'chat'); $('#build-workspace').toggleAttribute('hidden', workspace !== 'build'); $('#provider-controls').toggleAttribute('hidden', workspace !== 'chat');
  $('#page-title').textContent = workspace === 'chat' ? providerNames[ui.provider] : 'Build'; $('#page-subtitle').textContent = workspace === 'chat' ? 'Persistent provider workspace' : 'Managed local terminals and structured agent adapters';
  await window.wardenDesk.state.update({ workspace });
  if (workspace === 'chat') { providerBounds(); await window.wardenDesk.provider.show(ui.provider); } else { await window.wardenDesk.provider.hide(); queueMicrotask(() => fitActiveTerminal()); }
}
async function selectProvider(id: ProviderId): Promise<void> { ui.provider = id; document.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach((button) => button.classList.toggle('active', button.dataset.provider === id)); $('#page-title').textContent = providerNames[id]; await selectWorkspace('chat'); await window.wardenDesk.provider.show(id); }
function renderProviderStatus(status: ProviderStatus): void { ui.providerStatus.set(status.id, status); if (status.id !== ui.provider || ui.workspace !== 'chat') return; $('#page-subtitle').textContent = status.error || (status.loading ? 'Loading…' : status.title); document.querySelectorAll<HTMLButtonElement>('[data-action="back"]')[0].disabled = !status.canGoBack; document.querySelectorAll<HTMLButtonElement>('[data-action="forward"]')[0].disabled = !status.canGoForward; if (status.error) notice(status.error); if (status.cleared) notice(`${providerNames[status.id]} session data was cleared.`); }
function renderTabs(): void { const tabs = $('#terminal-tabs'); tabs.replaceChildren(); for (const [id, entry] of ui.terminals) { const button = document.createElement('button'); button.textContent = `${entry.metadata.name} · ${entry.metadata.status}`; button.classList.toggle('active', id === ui.activeTerminal); button.addEventListener('click', () => activateTerminal(id)); tabs.append(button); } }
function activateTerminal(id: string): void { const target = ui.terminals.get(id); if (!target) return; ui.activeTerminal = id; for (const [key, item] of ui.terminals) item.terminal.element?.toggleAttribute('hidden', key !== id); $('#terminal-empty').toggleAttribute('hidden', true); $('#terminal-state').textContent = `${target.metadata.status} · ${target.metadata.cwd}`; renderTabs(); fitActiveTerminal(); target.terminal.focus(); }
function fitActiveTerminal(): void { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (!active || ui.workspace !== 'build') return; try { active.fit.fit(); window.wardenDesk.terminal.resize(active.metadata.id, active.terminal.cols, active.terminal.rows); } catch { /* not visible yet */ } }
function attachTerminal(metadata: TerminalMetadata): void {
  const existing = ui.terminals.get(metadata.id); if (existing) { existing.metadata = metadata; renderTabs(); return; }
  const terminal = new Terminal({ cursorBlink: true, convertEol: true, fontSize: 13, fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', theme: { background: '#090c0a', foreground: '#dbe9d8', cursor: '#93bf90' }, scrollback: 10000 }); const fit = new FitAddon(); terminal.loadAddon(fit); terminal.open($('#terminal-container')); terminal.element?.toggleAttribute('hidden', true);
  const entry: UiTerminal = { metadata, terminal, fit, lineBuffer: '' }; ui.terminals.set(metadata.id, entry);
  terminal.onData((data) => { window.wardenDesk.terminal.write(metadata.id, data); if (data === '\r') { const command = entry.lineBuffer.trim(); if (command) { entry.metadata.history.push(command); entry.metadata.history = entry.metadata.history.slice(-200); void window.wardenDesk.terminal.recordCommand(metadata.id, command); } entry.lineBuffer = ''; } else if (data === '\u007f') entry.lineBuffer = entry.lineBuffer.slice(0, -1); else if (!data.startsWith('\u001b') && data >= ' ') entry.lineBuffer += data; });
  activateTerminal(metadata.id);
}
async function createTerminal(restore?: TerminalMetadata): Promise<void> { if (!ui.cwd && !restore?.cwd) { notice('Choose a valid project directory first.'); return; } try { const metadata = await window.wardenDesk.terminal.create({ name: restore?.name || `Terminal ${ui.terminals.size + 1}`, cwd: restore?.cwd || ui.cwd, restoreId: restore?.id }); ui.cwd = metadata.cwd; $('#active-directory').textContent = metadata.cwd; notice(); attachTerminal(metadata); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function selectExecution(mode: ExecutionMode): void { ui.execution = mode; document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.classList.toggle('active', button.dataset.execution === mode)); $('#terminal-workspace').toggleAttribute('hidden', mode !== 'local'); $('#agent-workspace').toggleAttribute('hidden', mode !== 'codex'); $('#adapter-status').toggleAttribute('hidden', mode === 'local' || mode === 'codex'); if (mode !== 'local' && mode !== 'codex') $('#adapter-copy').textContent = adapterCopy[mode]; else if (mode === 'local') fitActiveTerminal(); }

function runSummary(run: WardenRun): string { const recent = run.events.slice(-80).map((event) => { if (event.type === 'message.delta') return String(event.payload.delta || ''); if (event.type === 'command.started') return `\n$ ${String(event.payload.command || '')}\n`; if (event.type === 'command.completed') return `[exit ${String(event.payload.exitCode ?? '?')}]\n${String(event.payload.output || '').slice(-3000)}\n`; if (event.type === 'file.changed') return `[files changed: ${JSON.stringify(event.payload.changes || [])}]\n`; if (event.type === 'approval.requested') return `[approval required: ${String(event.payload.detail || '')}]\n`; if (event.type === 'run.completed') return `\nCompleted: ${String(event.payload.finalMessage || '')}`; if (event.type === 'run.failed') return `\nFailed: ${String(event.payload.error || '')}`; return ''; }).join(''); return [`Run ${run.id}`, `Status: ${run.status}`, `Project: ${run.cwd}`, `Thread: ${run.threadId || 'not started'}`, `Turn: ${run.turnId || 'not started'}`, `Changed files: ${run.evidence.changedFiles.join(', ') || 'none recorded'}`, `Tests: ${run.evidence.tests.map((test) => `${test.command} → ${test.exitCode}`).join('; ') || 'none recorded'}`, `Proof: local=${run.proof.local}, brain=${run.proof.brain}${run.proof.detail ? ` (${run.proof.detail})` : ''}`, '', recent || run.error || 'Waiting for events…'].join('\n'); }
function renderApprovals(run?: WardenRun): void { const root = $('#approval-list'); root.replaceChildren(); for (const approval of run?.approvals.filter((item) => item.status === 'pending') || []) { const card = document.createElement('div'); card.className = 'approval'; const title = document.createElement('strong'); title.textContent = approval.title; const detail = document.createElement('code'); detail.textContent = approval.detail; const once = document.createElement('button'); once.textContent = 'Approve once'; once.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'approve', 'once')); const session = document.createElement('button'); session.textContent = 'Approve session'; session.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'approve', 'session')); const deny = document.createElement('button'); deny.textContent = 'Deny'; deny.addEventListener('click', () => void respondApproval(run!.id, approval.id, 'deny', 'once')); card.append(title, detail, once, session, deny); root.append(card); } }
function renderRun(run?: WardenRun): void { if (!run) { $('#run-detail').textContent = 'Select or start a run.'; renderApprovals(); return; } ui.activeRun = run.id; ui.cwd = run.cwd; $('#active-directory').textContent = run.cwd; $('#agent-directory').textContent = run.cwd; $('#run-detail').textContent = runSummary(run); renderApprovals(run); document.querySelectorAll<HTMLButtonElement>('.run-card').forEach((card) => card.classList.toggle('active', card.dataset.runId === run.id)); }
function renderRuns(): void { const root = $('#runs'); root.replaceChildren(); const runs = [...ui.runs.values()].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)); for (const run of runs) { const button = document.createElement('button'); button.className = 'run-card'; button.dataset.runId = run.id; const title = document.createElement('strong'); title.textContent = run.prompt.split('\n')[0].slice(0, 80) || run.project; const meta = document.createElement('span'); meta.textContent = `${run.provider} · ${run.status} · ${new Date(run.updatedAt).toLocaleString()}`; button.append(title, meta); button.addEventListener('click', () => renderRun(run)); root.append(button); } if (ui.activeRun) renderRun(ui.runs.get(ui.activeRun)); }
async function refreshRuns(): Promise<void> { const runs = await window.wardenDesk.runs.list(); ui.runs = new Map(runs.map((run) => [run.id, run])); if (!ui.activeRun && runs[0]) ui.activeRun = runs[0].id; renderRuns(); }
async function respondApproval(runId: string, approvalId: string, decision: 'approve' | 'deny', scope: 'once' | 'session'): Promise<void> { try { await window.wardenDesk.runs.approve(runId, approvalId, decision, scope); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } }
function contextText(pack: ContextPack): string { return [`Project: ${pack.project}`, `Directory: ${pack.cwd}`, `Branch: ${pack.branch || 'unknown'}`, `Git status:\n${pack.gitStatus || '(clean)'}`, `Instructions: ${pack.instructionFiles.map((file) => file.path).join(', ') || 'none'}`, `Skills: ${pack.skills.join(', ') || 'none'}`, `Local scoped memories: ${pack.memories.length}`, `Warden Brain: ${pack.brainContext ? 'attached' : 'unavailable'}`, ...pack.warnings.map((warning) => `Warning: ${warning}`)].join('\n'); }

async function initialize(): Promise<void> {
  const { state, warning } = await window.wardenDesk.state.get(); if (warning) notice(warning); ui.provider = state.selectedProvider; ui.cwd = state.recentProjects[0] || ''; $('#active-directory').textContent = ui.cwd || 'No project selected';
  $('#agent-directory').textContent = ui.cwd || 'No project selected';
  for (const metadata of state.terminals) { const stopped = { ...metadata, status: 'stopped' as const }; attachTerminal(stopped); stopped && stopped.id === ui.activeTerminal; }
  document.querySelectorAll<HTMLButtonElement>('[data-workspace]').forEach((button) => button.addEventListener('click', () => void selectWorkspace(button.dataset.workspace as WorkspaceId)));
  document.querySelectorAll<HTMLButtonElement>('[data-provider]').forEach((button) => button.addEventListener('click', () => void selectProvider(button.dataset.provider as ProviderId)));
  document.querySelectorAll<HTMLButtonElement>('[data-action]').forEach((button) => button.addEventListener('click', () => void window.wardenDesk.provider.action(ui.provider, button.dataset.action as 'back' | 'forward' | 'reload' | 'stop' | 'home')));
  document.querySelectorAll<HTMLButtonElement>('[data-execution]').forEach((button) => button.addEventListener('click', () => selectExecution(button.dataset.execution as ExecutionMode)));
  $('#clear-session').addEventListener('click', async () => { if (confirm(`Clear all cookies and site data for ${providerNames[ui.provider]}? You will be signed out.`)) await window.wardenDesk.provider.clearSession(ui.provider); });
  $('#choose-directory').addEventListener('click', async () => { const cwd = await window.wardenDesk.terminal.chooseDirectory(); if (cwd) { ui.cwd = cwd; $('#active-directory').textContent = cwd; notice(); } });
  $('#agent-choose-directory').addEventListener('click', async () => { const cwd = await window.wardenDesk.terminal.chooseDirectory(); if (cwd) { ui.cwd = cwd; $('#active-directory').textContent = cwd; $('#agent-directory').textContent = cwd; notice(); } });
  $('#preview-context').addEventListener('click', async () => { if (!ui.cwd) return notice('Choose a project directory first.'); try { const pack = await window.wardenDesk.runs.previewContext(ui.cwd); const output = $('#context-preview'); output.textContent = contextText(pack); output.removeAttribute('hidden'); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#start-run').addEventListener('click', async () => { const prompt = ($('#run-prompt') as HTMLTextAreaElement).value.trim(); if (!ui.cwd || !prompt) return notice('Choose a project and enter a build task.'); try { notice('Starting Codex App Server run…'); const run = await window.wardenDesk.runs.start({ prompt, cwd: ui.cwd, attachContext: ($('#attach-context') as HTMLInputElement).checked }); ui.runs.set(run.id, run); ui.activeRun = run.id; renderRuns(); renderRun(run); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); await refreshRuns(); } });
  $('#resume-run').addEventListener('click', async () => { const prompt = ($('#run-prompt') as HTMLTextAreaElement).value.trim(); if (!ui.activeRun) return notice('Select a run to resume.'); try { notice('Resuming preserved Codex thread…'); const run = await window.wardenDesk.runs.resume(ui.activeRun, prompt); ui.runs.set(run.id, run); renderRun(run); notice(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#cancel-run').addEventListener('click', async () => { if (!ui.activeRun) return; try { await window.wardenDesk.runs.cancel(ui.activeRun); notice('Cancellation requested.'); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#generate-handoff').addEventListener('click', async () => { if (!ui.activeRun) return notice('Select a run first.'); try { const result = await window.wardenDesk.runs.handoff(ui.activeRun); $('#run-detail').textContent = `${result.content}\n\nSaved: ${result.path}`; notice('Handoff generated.'); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#save-proof').addEventListener('click', async () => { if (!ui.activeRun) return notice('Select a run first.'); try { const proof = await window.wardenDesk.runs.saveProof(ui.activeRun); notice(proof.detail); await refreshRuns(); } catch (error) { notice(error instanceof Error ? error.message : String(error)); } });
  $('#refresh-runs').addEventListener('click', () => void refreshRuns());
  $('#new-terminal').addEventListener('click', () => void createTerminal()); $('#clear-display').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; active?.terminal.clear(); });
  $('#restart-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active || active.metadata.status === 'running') return; active.terminal.dispose(); ui.terminals.delete(id); await createTerminal(active.metadata); });
  $('#close-terminal').addEventListener('click', async () => { const id = ui.activeTerminal; if (!id) return; const active = ui.terminals.get(id); if (!active) return; if (active.metadata.status === 'running' && !confirm(`Close ${active.metadata.name} and terminate its process?`)) return; await window.wardenDesk.terminal.kill(id); active.terminal.dispose(); ui.terminals.delete(id); ui.activeTerminal = ui.terminals.keys().next().value || null; if (ui.activeTerminal) activateTerminal(ui.activeTerminal); else $('#terminal-empty').removeAttribute('hidden'); renderTabs(); });
  const historyDialog = $('#history-dialog') as HTMLDialogElement; $('#show-history').addEventListener('click', () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; const list = $('#history-list'); list.replaceChildren(); for (const command of active?.metadata.history || []) { const li = document.createElement('li'); li.textContent = command; list.append(li); } historyDialog.showModal(); }); $('[data-close-dialog]').addEventListener('click', () => historyDialog.close()); $('#clear-history').addEventListener('click', async () => { const active = ui.activeTerminal ? ui.terminals.get(ui.activeTerminal) : undefined; if (active) { await window.wardenDesk.terminal.clearHistory(active.metadata.id); active.metadata.history = []; } historyDialog.close(); });
  window.wardenDesk.provider.onStatus(renderProviderStatus); window.wardenDesk.terminal.onData(({ id, data }) => ui.terminals.get(id)?.terminal.write(data)); window.wardenDesk.terminal.onState((metadata) => { const item = ui.terminals.get(metadata.id); if (item) item.metadata = metadata; renderTabs(); });
  window.wardenDesk.runs.onChanged((run) => { ui.runs.set(run.id, run); renderRuns(); if (ui.activeRun === run.id) renderRun(run); });
  new ResizeObserver(() => { providerBounds(); fitActiveTerminal(); }).observe(document.body); window.addEventListener('beforeunload', () => void window.wardenDesk.provider.hide());
  await refreshRuns(); await selectProvider(ui.provider); await selectWorkspace(state.workspace);
}
void initialize();
