import { contextBridge, ipcRenderer } from 'electron';
import type { DesktopApi, DesktopState, PlatformMenuAction, PlatformStatus, TerminalMetadata } from '../shared/types';

function subscribe<T>(channel: string, listener: (payload: T) => void): () => void { const handler = (_event: Electron.IpcRendererEvent, payload: T) => listener(payload); ipcRenderer.on(channel, handler); return () => ipcRenderer.removeListener(channel, handler); }
const api: DesktopApi = {
  app: { info: () => ipcRenderer.invoke('app:info') },
  state: { get: () => ipcRenderer.invoke('state:get'), update: (patch: Partial<Pick<DesktopState, 'workspace' | 'selectedProvider' | 'selectedPlatformId' | 'activeProjectId' | 'onboardingComplete' | 'mode'>>) => ipcRenderer.invoke('state:update', patch) },
  platform: { list: () => ipcRenderer.invoke('platform:list'), presets: () => ipcRenderer.invoke('platform:presets'), profiles: () => ipcRenderer.invoke('platform:profiles'), createProfile: (name) => ipcRenderer.invoke('platform:create-profile', name), renameProfile: (id, name) => ipcRenderer.invoke('platform:rename-profile', id, name), removeProfile: (id) => ipcRenderer.invoke('platform:remove-profile', id), create: (input) => ipcRenderer.invoke('platform:create', input), addPreset: (key, browserProfileId) => ipcRenderer.invoke('platform:add-preset', key, browserProfileId), update: (id, patch) => ipcRenderer.invoke('platform:update', id, patch), remove: (id) => ipcRenderer.invoke('platform:remove', id), removed: () => ipcRenderer.invoke('platform:removed'), restore: (id) => ipcRenderer.invoke('platform:restore', id), restoreDefaults: () => ipcRenderer.invoke('platform:restore-defaults'), show: (id, splitId) => ipcRenderer.invoke('platform:show', id, splitId), hide: () => ipcRenderer.invoke('platform:hide'), action: (id, action) => ipcRenderer.invoke('platform:action', id, action), openExternal: (id) => ipcRenderer.invoke('platform:open-external', id), clearSiteData: (id) => ipcRenderer.invoke('platform:clear-site-data', id), showMenu: (id, anchor) => ipcRenderer.invoke('platform:show-menu', id, anchor), setBounds: (bounds) => ipcRenderer.send('platform:set-bounds', bounds), onStatus: (listener: (status: PlatformStatus) => void) => subscribe('platform:status', listener), onMenuAction: (listener: (action: PlatformMenuAction) => void) => subscribe('platform:menu-action', listener) },
  project: { list: () => ipcRenderer.invoke('project:list'), create: (input) => ipcRenderer.invoke('project:create', input), createPlayground: () => ipcRenderer.invoke('project:create-playground'), activate: (id) => ipcRenderer.invoke('project:activate', id), update: (id, patch) => ipcRenderer.invoke('project:update', id, patch) },
  terminal: { list: () => ipcRenderer.invoke('terminal:list'), chooseDirectory: () => ipcRenderer.invoke('terminal:choose-directory'), create: (input) => ipcRenderer.invoke('terminal:create', input), write: (id, data) => ipcRenderer.send('terminal:write', id, data), resize: (id, cols, rows) => ipcRenderer.send('terminal:resize', id, cols, rows), kill: (id) => ipcRenderer.invoke('terminal:kill', id), clearHistory: (id) => ipcRenderer.invoke('terminal:clear-history', id), recordCommand: (id, command) => ipcRenderer.invoke('terminal:record-command', id, command), onData: (listener: (payload: { id: string; data: string }) => void) => subscribe('terminal:data', listener), onState: (listener: (terminal: TerminalMetadata) => void) => subscribe('terminal:state', listener) },
  runs: { providers: () => ipcRenderer.invoke('runs:providers'), checkProject: (cwd) => ipcRenderer.invoke('runs:check-project', cwd), list: (projectId) => ipcRenderer.invoke('runs:list', projectId), get: (id) => ipcRenderer.invoke('runs:get', id), previewContext: (cwd) => ipcRenderer.invoke('runs:preview-context', cwd), start: (input) => ipcRenderer.invoke('runs:start', input), resume: (id, prompt) => ipcRenderer.invoke('runs:resume', id, prompt), cancel: (id) => ipcRenderer.invoke('runs:cancel', id), approve: (runId, approvalId, decision, scope) => ipcRenderer.invoke('runs:approve', runId, approvalId, decision, scope), handoff: (id) => ipcRenderer.invoke('runs:handoff', id), saveProof: (id) => ipcRenderer.invoke('runs:save-proof', id), keep: (id) => ipcRenderer.invoke('runs:keep', id), discard: (id) => ipcRenderer.invoke('runs:discard', id), undoUpdate: (id) => ipcRenderer.invoke('runs:undo-update', id), onChanged: (listener) => subscribe('runs:changed', listener) },
};
contextBridge.exposeInMainWorld('wardenDesk', api);
