import { execFile } from 'node:child_process';
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs';
import { basename, join, relative } from 'node:path';
import { promisify } from 'node:util';
import type { ContextPack } from '../shared/types';
import { redact } from './redaction';
import { validateDirectory } from './terminal-manager';
const exec = promisify(execFile);
async function git(cwd: string, args: string[]): Promise<string> { try { return (await exec('git', ['-C', cwd, ...args], { timeout: 4000, maxBuffer: 1024 * 1024 })).stdout.trim(); } catch { return ''; } }
function readSafe(path: string, max = 5000): string { try { const stat = statSync(path); if (!stat.isFile() || stat.size > 512_000) return ''; return redact(readFileSync(path, 'utf8').slice(0, max)); } catch { return ''; } }
function skillNames(cwd: string): string[] { const names = new Set<string>(); for (const root of ['skills', '.agents/skills', '.codex/skills']) { const path = join(cwd, root); if (!existsSync(path)) continue; try { for (const item of readdirSync(path, { withFileTypes: true })) if (item.isDirectory()) names.add(item.name); } catch { /* optional */ } } return [...names].sort().slice(0, 50); }
function projectMemories(cwd: string): ContextPack['memories'] { const root = join(cwd, '_mctable/workbench/memories'); if (!existsSync(root)) return []; try { return readdirSync(root).filter((name) => name.endsWith('.json')).map((name) => { try { const path = join(root, name); return { path, mtime: statSync(path).mtimeMs, data: JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown> }; } catch { return null; } }).filter((item): item is NonNullable<typeof item> => Boolean(item)).filter((item) => item.data.repo_path === cwd || item.data.project_id === basename(cwd)).sort((a, b) => b.mtime - a.mtime).slice(0, 8).map(({ data }) => ({ id: String(data.memory_id || ''), kind: String(data.kind || 'memory'), summary: redact(String(data.summary || '')).slice(0, 500) })); } catch { return []; } }
export async function assembleContext(cwdInput: string): Promise<ContextPack> { const cwd = validateDirectory(cwdInput); const instructionFiles: ContextPack['instructionFiles'] = []; for (const name of ['AGENTS.md', 'CLAUDE.md', 'README.md']) { const path = join(cwd, name); const content = readSafe(path); if (content) instructionFiles.push({ path: relative(cwd, path), content }); } const [branch, gitStatus] = await Promise.all([git(cwd, ['branch', '--show-current']), git(cwd, ['status', '--short'])]); return { project: basename(cwd), cwd, branch: branch || undefined, gitStatus, instructionFiles, skills: skillNames(cwd), memories: projectMemories(cwd), assembledAt: new Date().toISOString(), warnings: instructionFiles.length ? [] : ['No AGENTS.md, CLAUDE.md, or README.md found at the project root.'] }; }
export function formatContext(pack: ContextPack): string { const sections = [`Project: ${pack.project}`, `Working directory: ${pack.cwd}`, `Branch: ${pack.branch || 'not detected'}`, `Git status:\n${pack.gitStatus || '(clean)'}`]; if (pack.instructionFiles.length) sections.push(`Instructions:\n${pack.instructionFiles.map((file) => `### ${file.path}\n${file.content}`).join('\n\n')}`); if (pack.skills.length) sections.push(`Available project skills: ${pack.skills.join(', ')}`); if (pack.memories.length) sections.push(`Relevant local Warden memories:\n${pack.memories.map((memory) => `- [${memory.kind}] ${memory.summary}`).join('\n')}`); if (pack.brainContext) sections.push(pack.brainContext); return `<warden-context>\n${sections.join('\n\n')}\n</warden-context>`; }
