import { execFile } from 'node:child_process';
import { readFileSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { promisify } from 'node:util';
import type { RunEvidence, WardenRun } from '../shared/types';
import { redact } from './redaction';
const exec = promisify(execFile);
async function git(cwd: string, args: string[], maxBuffer = 2 * 1024 * 1024): Promise<string> { try { return (await exec('git', ['-C', cwd, ...args], { timeout: 8000, maxBuffer })).stdout.trim(); } catch { return ''; } }
function statusPaths(status: string): string[] { return status.split('\n').filter(Boolean).map((line) => line.slice(3).trim()).map((path) => path.includes(' -> ') ? path.split(' -> ').at(-1)! : path); }
function untrackedDiff(cwd: string, status: string): string { const chunks: string[] = []; for (const line of status.split('\n').filter((entry) => entry.startsWith('?? '))) { const relative = line.slice(3).trim(); try { const path = join(cwd, relative); if (!statSync(path).isFile() || statSync(path).size > 200_000) continue; const content = redact(readFileSync(path, 'utf8')); chunks.push(`--- /dev/null\n+++ b/${relative}\n@@ new file @@\n${content.split('\n').map((row) => `+${row}`).join('\n')}`); } catch { /* binary or unreadable */ } } return chunks.join('\n\n'); }
export async function collectEvidence(run: WardenRun): Promise<RunEvidence> { const [status, trackedDiff] = await Promise.all([git(run.cwd, ['status', '--short']), git(run.cwd, ['diff', '--no-ext-diff', '--'])]); const tests = run.events.filter((event) => event.type === 'command.completed' && /(^|\s)(test|tests|--test|pytest|vitest|jest|npm\s+test|cargo\s+test|go\s+test)/i.test(String(event.payload.command || ''))).map((event) => ({ command: String(event.payload.command || ''), exitCode: typeof event.payload.exitCode === 'number' ? event.payload.exitCode : null, output: String(event.payload.output || '').slice(-12000) })); const completed = [...run.events].reverse().find((event) => event.type === 'run.completed'); const completedMessage = String(completed?.payload.finalMessage || ''); const finalItem = [...run.events].reverse().find((event) => event.type === 'tool.completed' && event.payload.itemType === 'agentMessage' && event.payload.text); const finalMessage = completedMessage || String(finalItem?.payload.text || '') || run.evidence.finalMessage; const diff = [trackedDiff, untrackedDiff(run.cwd, status)].filter(Boolean).join('\n\n'); return { ...run.evidence, gitStatusAfter: status, changedFiles: statusPaths(status), diff: diff.slice(0, 200_000), tests, finalMessage }; }
