import { basename } from 'node:path';
import type { BrowserWindow } from 'electron';
import type { ContextPack, ProofState, WardenRun } from '../shared/types';
import { CodexAppServerProvider } from './codex-adapter';
import { assembleContext } from './context-assembler';
import { collectEvidence } from './evidence';
import { createHandoff } from './handoff';
import { RunStore } from './run-store';
import { validateDirectory } from './terminal-manager';

export class RunManager {
  readonly store: RunStore; readonly codex: CodexAppServerProvider;
  constructor(userData: string, private readonly window: BrowserWindow) { this.store = new RunStore(userData); for (const run of this.store.list()) if (['starting', 'running', 'waiting_approval'].includes(run.status)) this.store.update(run.id, { status: 'interrupted', error: 'Warden AI Desk restarted while this run was active. Resume the preserved Codex thread to continue.' }); this.codex = new CodexAppServerProvider(this.store, (run) => this.window.webContents.send('runs:changed', run)); }
  list(): WardenRun[] { return this.store.list(); }
  get(id: string): WardenRun { const run = this.store.get(id); if (!run) throw new Error('Run not found.'); return run; }
  async previewContext(cwd: string, prompt = ''): Promise<ContextPack> { const pack = await assembleContext(cwd); const base = process.env.WARDEN_PRIVATE_URL || 'http://127.0.0.1:8125'; const projectId = basename(cwd).replace(/[^A-Za-z0-9_.-]/g, '-').slice(0, 160) || 'project'; try { const response = await fetch(`${base}/api/mcharness/memory/context-pack`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ project_id: projectId, repo_path: cwd, agent: 'codex_app_server', prompt, branch: pack.branch, max_memories: 8, max_chars: 6000 }), signal: AbortSignal.timeout(2500) }); const body = await response.json().catch(() => ({})) as Record<string, unknown>; if (response.ok && body.ok === true && typeof body.context === 'string') pack.brainContext = body.context; else pack.warnings.push(`Warden Brain context unavailable (${response.status}).`); } catch { pack.warnings.push('Warden Brain context unavailable; using repository-local context only.'); } return pack; }
  async start(input: { prompt: string; cwd: string; attachContext: boolean; model?: string }): Promise<WardenRun> { const cwd = validateDirectory(input.cwd); const prompt = String(input.prompt || '').trim(); if (!prompt || prompt.length > 100_000) throw new Error('Enter a build prompt under 100,000 characters.'); const context = input.attachContext ? await this.previewContext(cwd, prompt) : undefined; const handle = await this.codex.startRun({ prompt, project: basename(cwd), workingDirectory: cwd, model: input.model, context }); return this.get(handle.runId); }
  async resume(id: string, prompt: string): Promise<WardenRun> { await this.codex.resumeRun({ runId: id, prompt: String(prompt || '').trim() || undefined }); return this.get(id); }
  cancel(id: string): Promise<void> { return this.codex.cancelRun(id); }
  approve(runId: string, approvalId: string, decision: 'approve' | 'deny', scope?: 'once' | 'session'): Promise<void> { return this.codex.respondToApproval({ runId, approvalId, decision, scope }); }
  async handoff(id: string): Promise<{ path: string; content: string }> { let run = this.get(id); run = this.store.update(id, { evidence: await collectEvidence(run) }); const content = createHandoff(run); return { path: this.store.saveArtifact(id, 'handoff.md', content), content }; }
  async saveProof(id: string): Promise<ProofState> { let run = this.get(id); run = this.store.update(id, { evidence: await collectEvidence(run) }); const content = [`Warden AI Desk proof`, `Run: ${run.id}`, `Provider: ${run.provider}`, `Status: ${run.status}`, `Project: ${run.project}`, `Branch: ${run.evidence.branch || run.context?.branch || 'unknown'}`, `Changed files: ${run.evidence.changedFiles.join(', ') || 'none'}`, `Tests: ${run.evidence.tests.map((test) => `${test.command} => ${test.exitCode}`).join('; ') || 'none recorded'}`, `Result: ${run.evidence.finalMessage || run.error || 'none'}`].join('\n'); const path = this.store.saveArtifact(id, 'proof.txt', content); let proof: ProofState = { local: 'saved', brain: 'unavailable', path, detail: 'Saved locally. Warden private Brain service is unavailable.' }; const base = process.env.WARDEN_PRIVATE_URL || 'http://127.0.0.1:8125'; try { const response = await fetch(`${base}/api/mcharness/memory/remember`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ scope: 'warden', content, source: 'warden_ai_desk', title: `Proof: ${run.project} ${run.id}`, tags: ['desktop', 'codex', 'proof'], kind: 'proof', project_id: run.project, repo_path: run.cwd, branch: run.evidence.branch || run.context?.branch, agent_id: 'codex_app_server', metadata: { run_id: run.id, thread_id: run.threadId } }), signal: AbortSignal.timeout(3000) }); const body = await response.json().catch(() => ({})) as Record<string, unknown>; if (response.ok && body.ok === true) proof = { local: 'saved', brain: 'saved', path, detail: 'Saved locally and to Warden Brain.' }; else proof = { local: 'saved', brain: 'failed', path, detail: `Brain rejected proof (${response.status}): ${String(body.error || body.detail || 'unknown error')}` }; } catch (error) { proof = { local: 'saved', brain: 'unavailable', path, detail: `Saved locally; Brain unavailable: ${error instanceof Error ? error.message : String(error)}` }; } this.store.setProof(id, proof); this.window.webContents.send('runs:changed', this.get(id)); return proof; }
  shutdown(): void { this.codex.shutdown(); }
}
