"""Single source of truth for Warden model aliases."""
from __future__ import annotations
from typing import Any

ALIAS_DEFS: dict[str, dict[str, Any]] = {
    "warden-local": {
        "label": "Local",
        "description": "Intent classification, small summaries, cheap chat. Always private.",
        "primary_provider": "Ollama",
        "fallback_provider": "Groq",
        "privacy": "private",
        "openrouter_free_allowed": False,
        "cloud_allowed": False,
        "use_cases": ["classification", "summarisation", "routing", "cheap chat"],
        "max_context_tokens": 4096,
        "max_output_tokens": 512,
        "cost_tier": "free",
    },
    "warden-fast": {
        "label": "Fast",
        "description": "Agent replies, planning, quick code review. Groq/Cerebras primary.",
        "primary_provider": "Groq / Cerebras",
        "fallback_provider": "Ollama",
        "privacy": "private",
        "openrouter_free_allowed": False,
        "cloud_allowed": True,
        "use_cases": ["agent chat", "planning", "quick review", "tool synthesis"],
        "max_context_tokens": 8192,
        "max_output_tokens": 1024,
        "cost_tier": "free-tier",
    },
    "warden-free": {
        "label": "Free",
        "description": "Non-sensitive demos and experiments only. May log prompts.",
        "primary_provider": "OpenRouter (free)",
        "fallback_provider": "Groq",
        "privacy": "public-safe-only",
        "openrouter_free_allowed": True,
        "cloud_allowed": True,
        "use_cases": ["demos", "experiments", "public brainstorming"],
        "max_context_tokens": 4096,
        "max_output_tokens": 512,
        "cost_tier": "free",
        "warning": "OpenRouter free models may log prompts. No private repo/memory/env content.",
    },
    "warden-code": {
        "label": "Code",
        "description": "Repo task planning, patch review, implementation prompts.",
        "primary_provider": "Groq / Cerebras",
        "fallback_provider": "OpenRouter (free code)",
        "privacy": "private",
        "openrouter_free_allowed": False,
        "cloud_allowed": True,
        "use_cases": ["code review", "patch planning", "implementation", "debugging"],
        "max_context_tokens": 16384,
        "max_output_tokens": 2048,
        "cost_tier": "free-tier",
    },
    "warden-deep": {
        "label": "Deep",
        "description": "Architecture decisions, tricky diagnosis, final review.",
        "primary_provider": "Groq 70B / Cerebras 70B",
        "fallback_provider": "OpenRouter (free large)",
        "privacy": "private",
        "openrouter_free_allowed": False,
        "cloud_allowed": True,
        "use_cases": ["architecture", "root cause analysis", "design review", "complex synthesis"],
        "max_context_tokens": 32768,
        "max_output_tokens": 4096,
        "cost_tier": "free-tier",
    },
    "warden-embed": {
        "label": "Embed",
        "description": "Memory search, semantic retrieval. Local first.",
        "primary_provider": "Ollama (mxbai-embed-large)",
        "fallback_provider": "HuggingFace",
        "privacy": "private",
        "openrouter_free_allowed": False,
        "cloud_allowed": False,
        "use_cases": ["memory search", "semantic retrieval", "document indexing"],
        "max_context_tokens": 512,
        "max_output_tokens": 0,
        "cost_tier": "free",
    },
}

ALIAS_NAMES = list(ALIAS_DEFS.keys())
