#!/usr/bin/env bash
# Interactive setup for the Warden resident Telegram agent.
#
# Prompts for the Telegram bot token (no local echo) and allowed
# user/chat IDs, then writes them to a gitignored env file:
#   configs/warden_resident.env
#
# This script never prints secret values back to the terminal — only the
# variable names it set and the next commands to run.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$REPO_ROOT/configs"
ENV_FILE="$CONFIG_DIR/warden_resident.env"
GITIGNORE="$REPO_ROOT/.gitignore"

mkdir -p "$CONFIG_DIR"

echo "Warden Resident Telegram Agent — setup"
echo "---------------------------------------"
echo "You'll need a Telegram bot token from @BotFather (https://t.me/BotFather)."
echo "Never paste your token into a chat window or anywhere else it could be logged."
echo

read -r -s -p "Telegram bot token (input hidden): " TELEGRAM_BOT_TOKEN
echo
if [ -z "$TELEGRAM_BOT_TOKEN" ]; then
  echo "No token entered — aborting." >&2
  exit 1
fi

read -r -p "Allowed Telegram user ID(s), comma-separated (your numeric user id): " TELEGRAM_ALLOWED_USER_IDS
read -r -p "Allowed Telegram chat ID(s), comma-separated (optional, press enter to skip): " TELEGRAM_ALLOWED_CHAT_IDS

read -r -p "Warden private API base URL [http://127.0.0.1:8125]: " WARDEN_PRIVATE_BASE_URL
WARDEN_PRIVATE_BASE_URL="${WARDEN_PRIVATE_BASE_URL:-http://127.0.0.1:8125}"

read -r -p "Email mode (disabled|mock|gmail|imap) [disabled]: " EMAIL_MODE
EMAIL_MODE="${EMAIL_MODE:-disabled}"

read -r -p "Resident model profile (fast|balanced|deep) [fast]: " RESIDENT_MODEL_PROFILE
RESIDENT_MODEL_PROFILE="${RESIDENT_MODEL_PROFILE:-fast}"

umask 177
cat > "$ENV_FILE" <<EOF
# Warden resident agent configuration — generated by scripts/warden_resident_setup.sh
# This file contains a secret (TELEGRAM_BOT_TOKEN) — never commit it.
TELEGRAM_BOT_TOKEN=$TELEGRAM_BOT_TOKEN
TELEGRAM_ALLOWED_USER_IDS=$TELEGRAM_ALLOWED_USER_IDS
TELEGRAM_ALLOWED_CHAT_IDS=$TELEGRAM_ALLOWED_CHAT_IDS
WARDEN_PRIVATE_BASE_URL=$WARDEN_PRIVATE_BASE_URL
WARDEN_RESIDENT_DB=_mctable/resident/resident.sqlite
WARDEN_RESIDENT_DRY_RUN=false
EMAIL_MODE=$EMAIL_MODE
EMAIL_DRY_RUN=true
RESIDENT_MODEL_PROFILE=$RESIDENT_MODEL_PROFILE
RESIDENT_MAX_CONTEXT_ITEMS=8
RESIDENT_MAX_RESPONSE_CHARS=900
RESIDENT_ENABLE_DEEP_SYNTHESIS=false
EOF
chmod 600 "$ENV_FILE"

# Ensure the env file is gitignored.
if ! grep -qxF "configs/warden_resident.env" "$GITIGNORE" 2>/dev/null; then
  echo "configs/warden_resident.env" >> "$GITIGNORE"
fi

echo
echo "Config written to: $ENV_FILE (mode 600, gitignored)."
echo "Variables set: TELEGRAM_BOT_TOKEN, TELEGRAM_ALLOWED_USER_IDS, TELEGRAM_ALLOWED_CHAT_IDS,"
echo "  WARDEN_PRIVATE_BASE_URL, WARDEN_RESIDENT_DB, WARDEN_RESIDENT_DRY_RUN, EMAIL_MODE,"
echo "  EMAIL_DRY_RUN, RESIDENT_MODEL_PROFILE, RESIDENT_MAX_CONTEXT_ITEMS,"
echo "  RESIDENT_MAX_RESPONSE_CHARS, RESIDENT_ENABLE_DEEP_SYNTHESIS."
echo
echo "Next steps:"
echo "  set -a && source $ENV_FILE && set +a"
echo "  PYTHONPATH='.:src' .venv/bin/python -m warden.resident.telegram"
echo
echo "Or install the systemd unit: deploy/systemd/warden-resident-telegram.service.example"
