"""Proof Pack Generator for Warden Finish Subsystem.

Produces client-facing Markdown proof reports containing live URLs, redacted secret refs,
deployment IDs, acceptance test results, console/network summaries, repair logs, and N/N evidence claims.
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional
from datetime import datetime, timezone

from .models import FinishJob
from .secret_vault import SecretVault


class FinishProofPackGenerator:
    def __init__(self, output_dir: Optional[Path] = None, vault: Optional[SecretVault] = None):
        if output_dir is None:
            output_dir = Path.cwd() / "docs" / "proofs"
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.vault = vault or SecretVault()

    def generate_proof_pack(self, job: FinishJob) -> str:
        res = job.latest_acceptance_result
        passed_str = f"{res.passed_count}/{res.total_count}" if res else "N/A"

        lines = [
            f"# Warden Finish Proof Pack — {job.project}",
            "",
            f"- **Job ID**: `{job.job_id}`",
            f"- **Status**: `{job.current_stage.value}`",
            f"- **Objective**: {job.objective}",
            f"- **Preview URL**: {job.preview_url or 'N/A'}",
            f"- **Production URL**: {job.production_url or 'N/A'}",
            f"- **Functional Acceptance Score**: **{passed_str} Checks Passed**",
            f"- **Generated At**: `{datetime.now(timezone.utc).isoformat()}`",
            "",
            "## Executive Summary",
            "",
            f"Warden Finish executed the end-to-end finish pipeline for **{job.project}**.",
            f"The application was configured with Vercel and Supabase, verified through Playwright functional acceptance checks ({passed_str}), and promoted.",
            "",
            "## Provisioned Resources & Opaque Secret References",
            "",
        ]

        if job.secret_refs:
            for sref in job.secret_refs:
                lines.append(f"- Secret Ref: `{sref.ref_uri}` ({sref.description or 'Configured URI'})")
        else:

            lines.append("- No custom secret references required.")

        lines.extend([
            "",
            "## Functional Acceptance Evidence",
            "",
        ])

        if res and res.checks:
            for check in res.checks:
                status_icon = "✓" if check.passed else "✗"
                lines.append(f"- [{status_icon}] **{check.name}** ({check.category}): {check.details}")
        else:
            lines.append("- No acceptance test run recorded.")

        if res and res.screenshot_paths:
            lines.extend([
                "",
                "### Captured Screenshots",
                "",
            ])
            for shot in res.screenshot_paths:
                lines.append(f"- Screenshot: `{shot}`")

        lines.extend([
            "",
            "## Bounded Repair History",
            "",
        ])

        if job.repair_attempts:
            for att in job.repair_attempts:
                lines.append(f"- **Attempt #{att.attempt_index}** [{att.status}]: `{att.issue_class}` — {att.action_taken}")
        else:
            lines.append("- No repair loops were required. Pipeline passed cleanly.")

        lines.extend([
            "",
            "## Control Plane Actions & Approvals",
            "",
        ])

        for act in job.actions:
            lines.append(f"- Action `{act.action_type}` [{act.risk_class}]: {act.decision}")

        for app in job.approvals:
            lines.append(f"- Approval `{app.title}`: status `{app.status}` (Granted by: `{app.granted_by or 'operator'}`)")

        lines.extend([
            "",
            "---",
            "*Generated by Warden Finish Subsystem*",
        ])

        raw_content = "\n".join(lines)
        redacted_content = self.vault.redact_text(raw_content)

        file_path = self.output_dir / f"finish_proof_{job.job_id}.md"
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(redacted_content)

        job.proof_pack_path = str(file_path)
        return str(file_path)
